### PR TITLE
Fix: reform package

### PR DESCRIPTION
**Pull request by LinuxSuRen**
Use the function 'readMavenPom' instead of 'readFile'

@alauda/reviewers

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
The DSL of 'buildPlugin' is here https://github.com/jenkins-infra/pipeline-library/blob/master/vars/buildPlugin.groovy

**Comment by danielfbm** [comment]
so do we need to update any of the existing plugins? could you schedule an update?

**Comment by LinuxSuRen** [comment]
We will use `Alauda.Jenkinsfile` in Alauda's repo, then use `Jenkinsfile` in `Jenkinsci` repo.

**Comment by danielfbm** [comment]
good to merge

**Pull request merged**
