### PR TITLE
Feature: use the holder to replace version

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by danielfbm** [comment]
jenkins build failed: still fetching from .version file. Should we change to fetch from pom ?

**Comment by LinuxSuRen** [comment]
Already do this in #5 
So, we can merge #5 first.

**Comment by danielfbm** [comment]
what about this one?

**Comment by LinuxSuRen** [comment]
Already fix 
@danielfbm

**Pull request merged**
